# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('./Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
print(x[:,2])

['Female' 'Female' 'Female' ... 'Female' 'Male' 'Female']


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [8]:
print(x[:,2])

[0 0 0 ... 0 1 0]


*One Hot Encoding the "Geography" column*

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
et = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough') # [1] - refers to column index
x = np.array(et.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


one hot encoded column becomes the first column

In [11]:
print(x[:,1])

[0.0 0.0 0.0 ... 0.0 1.0 0.0]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print(x_train)
print(x_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


In [14]:
print(x_train.shape)
print(y_train.shape)

(8000, 12)
(8000,)


## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
model = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
model.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [16]:
model.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [17]:
model.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])  

 binary_crossentropy if binary predictions || categorical_crossentropy + softmax output layer for non bianry predictions

### Training the ANN on the Training set

In [19]:
model.fit(x_train, y_train, batch_size = 32, epochs = 100) # batch_size=32 - hypervalue/ default value

Epoch 1/100
250/250 [==============================] - 3s 5ms/step - loss: 0.6697 - accuracy: 0.6296
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.8020
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.8061
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4266 - accuracy: 0.8127
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4148 - accuracy: 0.8204
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4007 - accuracy: 0.8305
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3865 - accuracy: 0.8370
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3746 - accuracy: 0.8424
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3655 - accuracy: 0.8462
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3586 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

3 important things :
<ol>
    <li> double sq brackets - must be 2d array for predictions
    <li> look out for encoded variables
    <li> check for scaling and apply during prediction
</ol>

In [20]:
print(model.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [21]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1533   62]
 [ 210  195]]


0.864